version: '3'
services:

  data_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"

  web_app:
    build:
      context: ./src/app/client/
      dockerfile: Dockerfile
    ports:
      - "20000:80"

